### PR TITLE
Anthony stachowitz

### PR DESCRIPTION
**Pull request by stackBlock**
first pull - 1) questions done.
                 2) first part of mvp done (
                      ``` Configure an npm script named "server" that will execute your code using nodemon. Make 
                       nodemon be a development time dependency only, it shouldn't be deployed to production.
                        Configure an npm script named "start" that will execute your code using node. ```
)

### CODE REVIEW

**Comment by stackBlock** [comment]
Initial GET and Get w/id is working... tried to confuse by changing find() to get()... not nice..

**Comment by stackBlock** [comment]
Had a heart attack for a second - forgot to change "raw" body to JSON format at it wasn't working for a little while - thought about jumping of my roof - changed my mind upon remembering to change to JSON.

**Comment by stackBlock** [comment]
All CRUD works for actions and projects - I must configure errors now.

**Comment by stackBlock** [comment]
DONE MVP

**Review by ghost — APPROVED** [review]
Awesome job with CRUD; excellent job.

Grade: 2 (MVP)

**Pull request merged**
